### PR TITLE
Improve UI.

### PR DESCRIPTION
**Pull request by KartikSoneji**
## Changes:
- Change "1" and "2" to emojis.

- Updated output screen.

- Add `accept=".png,.jpg,.jpeg"` to file input to filter files shown in file chooser.

- Add `required` attribute to file input to prevent submission of empty form.

### CODE REVIEW

**Comment by tusharnankani** [comment]
@KartikSoneji 
I was about to make improvements in the User Interface, but no one could have done it better, loved the changes ^_^

**Comment by HarshKapadia2** [comment]
Thank you, @tusharnankani for considering making improvements! 💛 
I agree with you! @KartikSoneji is awesome and I love the changes as well! 🔥

**Review by HarshKapadia2 — APPROVED** [review]
This looks SO good! Well done!
Thank you so much, @KartikSoneji!

**Comment by HarshKapadia2** [comment]
I would've liked more atomic commits @KartikSoneji.

**Comment by tusharnankani** [comment]
@HarshKapadia2 
> I would've liked more atomic commits @KartikSoneji.

What do you mean by atomic commits? Does it mean a different PR for every different file commit?

**Comment by HarshKapadia2** [comment]
More commits in the same PR.
More commits with each change being one commit (atomic commits) and in the same PR because all the changes are related.

**Pull request merged**
