### PR TITLE
Add 404 page html

### PR DESCRIPTION
**Pull request by Haroonchik**

### CODE REVIEW

**Comment by HarshKapadia2** [comment]
- The error text is quite unreadable. I would prefer the same font as the entire site with a picture (if you feel like it).
- Nice thinking of adding a button, but please let the text be 'Home' instead of 'Main'.



---

I just realised that it would be better if there was one common template for all errors where the error code (Eg: 404, 500) and error message (Eg: NOT FOUND, INTERNAL SERVER ERROR) were just passed in as and when the error occurred.

Example:
A Node.js project [Food Oye](https://github.com/rajatrjoshi/food-oye/blob/master/views/error.ejs) that I had done. ([Live web app](https://food-oye.herokuapp.com/jshdjs))

The `status`, `status_descp` and `err_trace` in the 1st pic get populated in the final output (2nd pic)

image



A similar thing has to be done in Flask.

Do you think you can do this? Sorry for changing the original issue. If you can't take it up, it's completely okay, but just let me know.

**Comment by HarshKapadia2** [comment]
Let me know if you can make the new changes that I suggested. If not, I'll accept this PR and then make another issue for that. If you take up the new issue, I'll close this PR and issues #6 and #7 and create a new issue that you can take up. A lot of the code from this PR will be the same for the new issue, so you will just have to make some additions. Let me know your decision.

**Comment by Haroonchik** [comment]
@HarshKapadia2  Let's then accepted this PR and in the new one I will try to do the task that you described above.

**Comment by HarshKapadia2** [comment]
Wouldn't it be better to directly go to a new PR?

If you're not able to do the new PR, I'll merge this one. I'll not close this PR until that new PR is merged.
So finish the tasks for this PR and then use the same code for the new PR, just adding in the dynamic stuff.
Tasks for this PR (as mentioned above):
> The error text is quite unreadable. I would prefer the same font as the entire site with a picture (if you feel like it).
Nice thinking of adding a button, but please let the text be 'Home' instead of 'Main'.

Let me know what you think.

**Comment by Haroonchik** [comment]
@HarshKapadia2 Ok, I got it, I close the tasks for this PR and then open a new one to add a dynamic display of the error code.

**Comment by HarshKapadia2** [comment]
Finish this PR's tasks and then leave it alone.
I will make a new issue for the new PR. Open a PR once I make that new issue.

**Comment by Haroonchik** [comment]
@HarshKapadia2 Use a picture that is in the title?

**Comment by HarshKapadia2** [comment]
Yeah that will work.
It is a `.ico` file though. Don't use that. Use the [`SVG` version](https://www.svgrepo.com/svg/55645/fist).

**Comment by Haroonchik** [comment]
@HarshKapadia2 Check.

**Comment by HarshKapadia2** [comment]
> Nice thinking of adding a button, but please let the text be 'Home' instead of 'Main'.

Just make this change. Everything else is fine!

**Comment by Haroonchik** [comment]
@HarshKapadia2 done

**Comment by HarshKapadia2** [comment]
Awesome!
You can now start working on issue #20.

**Comment by Haroonchik** [comment]
@HarshKapadia2 Can you merge this PR ? I want to get data to master

**Comment by HarshKapadia2** [comment]
But the point was to use this new code to make a new PR altogether and merge this PR only if you aren't able to complete the new PR.

**Comment by Haroonchik** [comment]
@HarshKapadia2 I have a problem when I push changes from another branch, all commits from this PR are also pushed to the new PR. I have already done dynamic rendering but can't push correctly.

**Comment by Haroonchik** [comment]
@HarshKapadia2 Hello, check this PR pleace

**Pull request closed without merging**
